kind: PersistentVolumeClaim
apiVersion: v1
metadata:
  name: discourse
  labels:
    app.kubernetes.io/managed-by: Helm
  annotations:
    "helm.sh/hook": pre-install
    "helm.sh/hook-weight": "-10"
    "helm.sh/resource-policy": keep
    "helm.sh/hook-delete-policy": hook-failed
    meta.helm.sh/release-name: "{{ .Release.Name }}"
    meta.helm.sh/release-namespace: "{{ .Release.Namespace }}"
spec:
  accessModes:
    - ReadWriteMany
  resources:
    requests:
      storage: 10Gi
