kind: Deployment
apiVersion: apps/v1
metadata:
  name: discourse
  annotations:
    description: Defines how to deploy Discourse all in one
spec:
  replicas: 2
  selector:
    matchLabels:
      app: discourse
  template:
    metadata:
      labels:
        app: discourse
    spec:
      initContainers:
      - name: init
        image: abraverm/discourse
        imagePullPolicy: Always
#        image: "image-registry.openshift-image-registry.svc:5000/central-ci/discourse"
        env:
          - name: RAILS_ENV
            value: "production"
          - name: DISCOURSE_DB_SOCKET
            value: ''
          - name: DISCOURSE_DB_PORT
            value: '5432'
          - name: DISCOURSE_DB_NAME
            value: 'discourse'
          - name: DISCOURSE_DB_PASSWORD
            value: 'postgres'
          - name: DISCOURSE_DB_USERNAME
            value: 'postgres'
          - name: DISCOURSE_DB_HOST
            value: "discourse-postgresql-ha-pgpool.central-ci.svc.cluster.local"
          - name: DISCOURSE_REDIS_HOST
            value: "discourse-redis-ha-haproxy.central-ci.svc.cluster.local"
          - name: DISCOURSE_REDIS_PORT
            value: "6379"
        command: ["/bin/bash", "/scripts/init.sh", "-u", "abraverm@redhat.com", "-p", "redhatredhatredhat"]
        volumeMounts:
          - name: discourse
            mountPath: /var/www/discourse
          - name: scripts
            mountPath: /scripts
      containers:
      - name: discourse
        image: abraverm/discourse
        imagePullPolicy: Always
#        image: " "
        command: ["/var/www/discourse/bin/unicorn"]
        env:
          - name: UNICORN_SIDEKIQS
            value: "0"
          - name: RAILS_ENV
            value: "production"
          - name: UNICORN_WORKERS
            value: "3"
          - name: UNICORN_SIDEKIQS
            value: "1"
          - name: RUBY_GLOBAL_METHOD_CACHE_SIZE
            value: "131072"
          - name: RUBY_GC_HEAP_GROWTH_MAX_SLOTS
            value: "40000"
          - name: RUBY_GC_HEAP_INIT_SLOTS
            value: "400000"
          - name: RUBY_GC_HEAP_OLDOBJECT_LIMIT_FACTOR
            value: "1.5"
          - name: DISCOURSE_DB_SOCKET
            value: ''
          - name: DISCOURSE_DB_PORT
            value: '5432'
          - name: DISCOURSE_DB_NAME
            value: 'discourse'
          - name: DISCOURSE_DB_PASSWORD
            value: 'postgres'
          - name: DISCOURSE_DB_USERNAME
            value: 'postgres'
          - name: DISCOURSE_DB_HOST
            value: "discourse-postgresql-ha-pgpool.central-ci.svc.cluster.local"
          - name: DISCOURSE_REDIS_HOST
            value: "discourse-redis-ha-haproxy.central-ci.svc.cluster.local"
          - name: DISCOURSE_REDIS_PORT
            value: "6379"
          - name: DISCOURSE_DEVELOPER_EMAILS
            value: "abraverm@redhat.com"
          - name: DISCOURSE_HOSTNAME
            value: "discourse.apps.ocp.prod.psi.redhat.com"
          - name: DISCOURSE_SMTP_ADDRESS
            value: "smtp.example.com"
          - name: DISCOURSE_SERVE_STATIC_ASSETS
            value: "true"
          - name: DISCOURSE_MAX_REQS_PER_IP_MODE
            value: "warn"
        ports:
        - name: http
          containerPort: 8080
          protocol: TCP
        volumeMounts:
          - mountPath: "/var/www/discourse"
            name: discourse
        resources:
          limits:
            cpu: 2
            memory: 4Gi
      volumes:
        - name: discourse
          persistentVolumeClaim:
            claimName: discourse
        - name: scripts
          configMap:
            name: discourse

